### ISSUE TITLE
Is it possible to modify this to protect more people without protecting malicious groups?

### ISSUE THREAD

**Issue by colejd** [ContributorCovenant/hippocratic-license#10]
Hello!

Let me first say thank you for this. I'm very happy this exists, and I've wanted something like this for a long time. With that in mind, I wanted to start a discussion on the topic of modifying the language of this license to try to improve its coverage without harming its goals in doing so.

> * The software may not be used by individuals, corporations, governments, or other groups for systems or activities that actively and knowingly endanger, harm, or otherwise threaten the physical, mental, economic, or general well-being of underprivileged individuals or groups in violation of the United Nations Universal Declaration of Human Rights (https://www.un.org/en/universal-declaration-human-rights/).

I've noticed a few people here and on Twitter taking issue with the use of the term "underprivileged". I've seen the rationale in #2:
> This change makes it a little more difficult to maliciously interpret the harm clause to protect groups in power.

This is a complicated topic. Removing the term "underprivileged" would make it easier for the harm clause to be used to protect groups in power. I do however think it is too reductive. As a thought experiment, let's say I make a computer vision library that implements face detection with this license, and a government agency uses my library to make a drone. They then use that drone to kill a person who this license would describe as underprivileged, and someone who is not. Should both instances of harm not be considered?

This is specifically what I was hoping to discuss. Is it possible to modify the language of this license in a way that offers more people protection without reducing its effectiveness or making it easier to abuse the license?

Whatever it is needs to be carefully considered, as we don't want to protect malicious groups that this license is intended to stop. Let's say we make a change with the above in mind. Let's also say I write a CSS framework under this license, and a member of a harmful group uses this framework to make a website unrelated to their activities. They themselves may not directly cause harm by doing this, but I certainly wouldn't want them using my framework (the harm not being direct is debatable, but bear with me). Are there changes that can be made to limit the potential for "indirect" harm in this manner?

Thank you for your time.

**Comment by sarahdayan** [comment]
Related issue: https://github.com/ContributorCovenant/hippocratic-license/issues/4

This was fixed in https://github.com/ContributorCovenant/hippocratic-license/commit/f207476db54cfb92d40c05cb4fa7dede0acc44f7 so this issue could be closed.
