### ISSUE TITLE
List of adopters 

### ISSUE THREAD

**Issue by rafaelcastrocouto** [ContributorCovenant/hippocratic-license#13]
We add to the `readme.md` or we could create a wiki page where we can place a project list with Hippocratic license adopters.

**Comment by ghost** [comment]
If I understand the proposed workflow correctly, a PR for `content/adopters.md` should be created.

**Comment by rafaelcastrocouto** [comment]
How did I miss that, it's in the readme:

> Adding a Project to the List of Adopters
> Fork the repository.
> Add a new row to the adopters.csv file, with the project name in the first column, and the project URL in the second column.
> Open a pull request
