### ISSUE TITLE
adopters.csv contains many projects that don't use this license

### ISSUE THREAD

**Issue by ghost** [ContributorCovenant/hippocratic-license#17]
The file `adopters.csv` contains many projects that don't use this license. Just as an example, the file [lists Eclipse](https://github.com/ContributorCovenant/hippocratic-license/blob/release/public/adopters.csv#L51) as an adopter. This is wrong, Eclipse [uses the  EPL 2.0](https://www.eclipse.org/legal/epl-2.0/).

This file must only contain projects that actually use this license. Listing projects like Atom, Curl, Eclipse, Golang and many others is just plain wrong.

**Comment by CoralineAda** [comment]
This was a cache that carried over from a previous project. I've updated the `.gitignore` to keep the cache out of the repo. Thanks for catching this!
