### ISSUE TITLE
Only "underprivileged"?

### ISSUE THREAD

**Issue by AllenJB** [ContributorCovenant/hippocratic-license#4]
Ignoring the complete lack of definition of what exactly "underprivileged" means that I suspect makes the enforceability of this clause dubious at best, why only "underprivileged"?

Does that mean that I could use code under this license if I were, for example, to threaten harm to all the citizens of a given country regardless of their wealth?

What does this mean in the case of, for example, a company writing software involved in weapons where the developer has no idea against whom the system might be employed?

**Comment by Mikotochan** [comment]
The underprivileged thing was introduced by https://github.com/ContributorCovenant/hippocratic-license/pull/2

**Comment by donatj** [comment]
This updated wording is really problematic. It indicates that is is explicitly OK to use my software in killer robots/drones as long as the people it’s killing aren’t underprivileged. I don’t want my software used to kill *anyone* regardless of privilege.

**Comment by tevko** [comment]
At the very least, the name of this document should be changed, being that the wording therein is extremely misleading. The [Hippocratic](https://en.wikipedia.org/wiki/Hippocratic_Oath) / [Osteopathic](https://en.wikipedia.org/wiki/Osteopathic_Oath) oaths explicitly state not harming any person, regardless of perceived status

**Comment by roryokane** [comment]
It looks like commit f207476db54cfb92d40c05cb4fa7dede0acc44f7 has fixed this problem by removing the word “underprivileged”. [The current version of this license](https://firstdonoharm.dev/version/1/1/license.html) doesn’t restrict the “individuals and groups” that the restriction applies to.

**Comment by nateberkopec** [comment]
I think this was fixed in 1.1 and this issue can be closed.
