### ISSUE TITLE
New website UI layout width

### ISSUE THREAD

**Issue by rafaelcastrocouto** [ContributorCovenant/hippocratic-license#41]
After the last update (https://github.com/ContributorCovenant/hippocratic-license/pull/39) the website content is being squished to a very small column if the window width is between 640px and 800px.

Screenshot:
![Untitled](https://user-images.githubusercontent.com/422159/74536460-e2226080-4f16-11ea-85a3-0cd5834dacdf.png)

Since there are multiple solutions I'm just leaving the issue here and propose one solution, so we can discuss the best way to fix it.

I would change the line 344 of main.css ` border-left: 30rem solid var(--color-primary-lighter); ` to a percentage instead of a fixed rem.

**Comment by CoralineAda** [comment]
Fixed, thanks so much for pointing this out!

**Comment by rafaelcastrocouto** [comment]
Looking great now, cheers!
I miss the colorful background though ❤
