### ISSUE TITLE
Current license text allows the licensor to terminate license without cause, only based on allegations

### ISSUE THREAD

**Issue by ryan-lane** [ContributorCovenant/hippocratic-license#43]
The current license text can allow a licensor to terminate a license, as long as an allegation is made, effectively making it possible for the licensor to terminate a license, even if the licensee is not actually abusing human rights.

This can be an easy vector for trolls to extort companies.

**Comment by CoralineAda** [comment]
We’re considering an arbitration mechanism here.

**Comment by CoralineAda** [comment]
Please see the PR for the 2.1 version, which includes arbitration language. Feedback welcome!
