### ISSUE TITLE
Use Plausible or Matomo instead of Google Analytics on firstdonoharm.dev

### ISSUE THREAD

**Issue by realpixelcode** [ContributorCovenant/hippocratic-license#89]
In order to protect the visitors' privacy, please stop using Google Analytics and use a privacy-friendly alternative like Plausible or Matomo instead.

https://webbkoll.dataskydd.net/en/results?url=http%3A%2F%2Ffirstdonoharm.dev%2F#sri
https://privacyscore.org/site/196604/#collapse1_1

**Comment by CoralineAda** [comment]
Closed in #90 , thank you!
